channels:
  - information/rules-and-info
  - information/roles
  - announcements/server
  - announcements/social
  - announcements/promo
  - Secrets/committee
  - Secrets/moderators
  - Secrets/sponsors
  - Secrets/community-heroes
  - Development/getting-started
  - Development/general
  - Development/back-end
  - Development/front-end
  - Development/mobile
  - jobs/job-advice
  - jobs/job-adverts
  - jobs/job-discuss
  - jobs/worklog
  - Social/introductions
  - Social/general
  - Social/personal-finance
  - Social/rage-room
  - Social/food
  - Social/pets
  - Social/sofa-studies
  - Social/music
  - Social/battlestations
  - Social/sports
  - Social/blockchain
  - Hobbies/fitness
  - Hobbies/gaming
  - Hobbies/art
  - Hobbies/coffee
  - News/current-affairs
  - News/tech-news
  - nordevcon/nordevcon
  - nordevcon/track-1
  - nordevcon/track-2
  - nordevcon/track-3
  - nordevcon/pioneering
  - nordevcon/staff
  - 🔊 Voice Channels/voice-chat-text
  - 🔊 Voice Channels/watercooler
  - 🔊 Voice Channels/committee-voice
  - 🔊 Voice Channels/development
  - 🔊 Voice Channels/development-two
  - 🔊 Voice Channels/gaming
  - 🔊 Voice Channels/gaming-two
  - 🔊 Voice Channels/events
